# Generated by Django 2.1 on 2018-08-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200, verbose_name='Source file path from static folder')),
                ('alt', models.CharField(max_length=200, verbose_name='Alternative text for image')),
                ('caption_h3', models.CharField(max_length=200, verbose_name='Caption header in caursel img')),
                ('caption_p', models.CharField(max_length=200, verbose_name='Caption Para in Caurosel img')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretly.MessageType'),
        ),
    ]
